#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ICONS_DIR = path.join(__dirname, '..', 'src', 'assets', 'icons');
const OUTPUT_FILE = path.join(
	__dirname,
	'..',
	'src',
	'assets',
	'icons',
	'icon-registry.ts',
);

console.log('🎨 Building icon registry...\n');

// Read all SVG files
const files = fs
	.readdirSync(ICONS_DIR)
	.filter((file) => file.endsWith('.svg'))
	.sort();

if (files.length === 0) {
	console.error('❌ No SVG files found in', ICONS_DIR);
	process.exit(1);
}

const icons = {};

// Parse each SVG file
files.forEach((file) => {
	const iconName = path.basename(file, '.svg');
	const filePath = path.join(ICONS_DIR, file);
	const svgContent = fs.readFileSync(filePath, 'utf-8');

	// Extract viewBox
	const viewBoxMatch = svgContent.match(/viewBox="([^"]+)"/);
	const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24';

	// Extract content between <svg> tags (remove svg wrapper)
	const contentMatch = svgContent.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
	const content = contentMatch
		? contentMatch[1].trim()
		: '<path d="M0 0h24v24H0z" fill="none"/>';

	icons[iconName] = {
		viewBox,
		content,
	};

	console.log(`✓ ${iconName}`);
});

// Generate TypeScript content
const iconNames = Object.keys(icons);
const typeDefinition = iconNames.map((name) => `\t| '${name}'`).join('\n');

const iconEntries = Object.entries(icons)
	.map(([name, data]) => {
		// Escape backticks and backslashes in content
		const escapedContent = data.content
			.replace(/\\/g, '\\\\')
			.replace(/`/g, '\\`')
			.replace(/\$/g, '\\$');

		return `\t'${name}': {
		viewBox: '${data.viewBox}',
		content: \`${escapedContent}\`,
	}`;
	})
	.join(',\n');

const output = `/**
 * Auto-generated icon registry
 * DO NOT EDIT MANUALLY - Generated by scripts/build-icons.mjs
 * Run 'npm run build:icons' to regenerate
 */

export type IconName =
${typeDefinition};

export interface IconData {
	viewBox: string;
	content: string;
}

export const iconRegistry: Record<IconName, IconData> = {
${iconEntries},
};

/**
 * Get icon data by name
 */
export function getIcon(name: IconName): IconData | undefined {
	return iconRegistry[name];
}

/**
 * Check if an icon exists in the registry
 */
export function hasIcon(name: string): name is IconName {
	return name in iconRegistry;
}

/**
 * Get all available icon names
 */
export function getIconNames(): IconName[] {
	return Object.keys(iconRegistry) as IconName[];
}
`;

// Write output file
fs.writeFileSync(OUTPUT_FILE, output);

console.log(`\n✨ Generated icon registry with ${iconNames.length} icons`);
console.log(`📄 Output: ${OUTPUT_FILE}\n`);
