import { setCustomElementsManifest } from '@storybook/web-components';
import type { Preview } from '@storybook/web-components-vite';
import { spyOn } from 'storybook/test';

// Import CSS variables
import '../src/styles/variables.css';

// Import custom elements manifest for better prop documentation
// This file is generated by running: npm run build:metadata
try {
	const customElements = await import('../custom-elements.json', {
		with: { type: 'json' },
	});
	setCustomElementsManifest(customElements.default);
} catch (e) {
	console.warn(
		'Custom elements manifest not found. Run `npm run build:metadata` to generate it.',
	);
}

const preview: Preview = {
	parameters: {
		controls: {
			matchers: {
				color: /(background|color)$/i,
				date: /Date$/i,
			},
		},
		docs: {
			toc: true, // Show table of contents in docs
		},
		actions: { argTypesRegex: '^on[A-Z].*' }, // Auto-detect event handlers
	},
	async beforeEach() {
		spyOn(console, 'log').mockName('console.log');
	},
};

export default preview;
